crp_img_list = {'BCH': 'https://cdn.coinranking.com/SkdJqSuuW/bch.svg',
'ICX': 'https://cdn.coinranking.com/media/12318192/icx.png?width=46',
'IOT': 'https://cdn.coinranking.com/H1IQ9Bdd-/miota.svg',
'NEO': 'https://cdn.coinranking.com/Bkop5Hu_Z/neo.svg',
'QTUM': 'https://cdn.coinranking.com/HJ7woSuuW/qtum.svg',
'TRX': 'https://cdn.coinranking.com/B10WKs76Z/trx.svg', 'XEM': 'https://cdn.coinranking.com/Bkvu9rOOZ/xem.svg', 'WAVES': 'https://cdn.coinranking.com/B1tzRbyMz/waves.svg','DOGE':'https://cdn.coinranking.com/H1arXIuOZ/doge.svg', 'ARK': 'https://cdn.coinranking.com/HyWBr8_OW/ark.svg', 'ETC': 'https://cdn.coinranking.com/rJfyor__W/etc.svg', 'LTC': 'https://cdn.coinranking.com/HyZL5BOOb/ltc.svg', 'VERI': 'https://cdn.coinranking.com/SJE0orHtW/veri.svg', 'STRAT': 'https://cdn.coinranking.com/SyEuoBu_W/strat.svg',
'MONA': 'https://cdn.coinranking.com/SkxEgPdd-/mona.svg', 'PIVX': 'https://cdn.coinranking.com/BknhDIOu-/pivx.svg','DCR':'https://cdn.coinranking.com/SyJaBU_dZ/dcr.svg', 'DGB': 'https://cdn.coinranking.com/SyzuwIudW/dgb.svg', 'HSR': 'https://cdn.coinranking.com/HJ6OlzVKW/hsr.svg', 'ETH': 'https://cdn.coinranking.com/rk4RKHOuW/eth.svg', 'SALT': 'https://cdn.coinranking.com/BkEvjH0ib/salt.svg', 'SC': 'https://cdn.coinranking.com/Hkvu-8d_-/sc.svg', 'ZEC': 'https://cdn.coinranking.com/rJrKiS_uZ/zec.svg',
'ADA': 'https://cdn.coinranking.com/ryY28nXhW/ada.svg', 'BNB':'https://cdn.coinranking.com/B1N19L_dZ/bnb.svg', 'DASH': 'https://cdn.coinranking.com/BkIK5rOd-/dash.svg', 'BTC': 'https://cdn.coinranking.com/Sy33Krudb/btc.svg', 'ARDR': 'https://cdn.coinranking.com/HyZRH8d_W/ardr.svg', 'XRB': 'https://cdn.coinranking.com/B1b-YYaWG/xrb.svg', 'USDT': 'https://cdn.coinranking.com/SJs1nH_OZ/usdt.svg', 'EOS': 'https://cdn.coinranking.com/H1YjiSd_-/eos.svg', 'PPT': 'https://cdn.coinranking.com/HyCw7LOdZ/ppt.svg',
'BCN': 'https://cdn.coinranking.com/rkpGWI_OZ/bcn.svg',
'KMD': 'https://cdn.coinranking.com/SyobU8dOb/kmd.svg',
'REP': 'https://cdn.coinranking.com/H1GlZLd_Z/rep.svg',
'XMR': 'https://cdn.coinranking.com/Syz-oSd_Z/xmr.svg',
'BCC': 'https://cdn.coinranking.com/SJN4sHdO-/bcc.svg', 'BTS': 'https://cdn.coinranking.com/B1TCoS_O-/bts.svg',
'XVG': 'https://cdn.coinranking.com/SklJgPdu-/xvg.svg',
'LSK': 'https://cdn.coinranking.com/SydghSdub/lsk.svg',
'IGNIS': 'https://cdn.coinranking.com/media/1384046/ignis.png?width=46',
'OMG': 'https://cdn.coinranking.com/BJGUoHu_Z/omg.svg',
'XRP': 'https://cdn.coinranking.com/Bkuz9Hd_-/xrp.svg', 'BTG': 'https://cdn.coinranking.com/BkLedkw-G/btg.svg', 'NXT': 'https://cdn.coinranking.com/rkEsD8u_W/nxt.svg', 'SNT': 'https://cdn.coinranking.com/B1MQMP__Z/snt.svg', 'STEEM': 'https://cdn.coinranking.com/SkkCsr_OW/steem.svg', 'ETN': 'https://cdn.coinranking.com/HJvOCDlyM/etn.svg', 'GNT': 'https://cdn.coinranking.com/rkzb-Uuu-/gnt.svg', 'XLM': 'https://cdn.coinranking.com/HyAEXLuOZ/xlm.svg',
'PART':'https://cdn.coinranking.com/rJpP2xB6b/part.svg','UNITY':'https://cdn.coinranking.com/media/350935/unity_1.png?width=80','EDG':'https://cdn.coinranking.com/HJ0AdUuO-/edg.svg','BURST':'https://cdn.coinranking.com/media/16746623/burst.png?width=80','CTR':'https://cdn.coinranking.com/media/1384029/ctr.png?width=80'}
